<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <!-- Spring Boot Parent -->
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.0</version>
    <relativePath/>
  </parent>

  <groupId>org.retailbank360</groupId>
  <artifactId>retailbank360</artifactId>      <!-- container project  -->
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>                  <!-- convert parent pom  -->

  <name>retailbank360</name>
  <url>http://maven.apache.org</url>
  <modules>
    <module>retailbank-common</module>
    <module>retailbank-api-gateway</module>
    <module>retailbank-customer-service</module>
    <module>retailbank-account-service</module>
    <module>retailbank-transaction-service</module>
    <module>retailbank-notification-service</module>
    <module>retailbank-loan-service</module>
    <module>retailbank-audit-service</module>
    <module>retailbank-auth-service</module>
  </modules>

  <properties>
    <java.version>17</java.version>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <spring-cloud.version>2025.0.0</spring-cloud.version>
    <jjwt.version>0.12.6</jjwt.version>
    <springdoc.version>2.8.9</springdoc.version>
    <lombok.version>1.18.38</lombok.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>${lombok.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>
