-- Baseline schema for retailbank-audit-service (postgresql).
--
-- Generated from the JPA mappings, so the migration and the entities agree by construction.
-- Hibernate runs in 'validate' mode against this: a mapping change without a matching migration
-- stops the service at startup rather than letting the schema drift silently.
--
-- Never edit this file once it has been applied anywhere. Add V2__, V3__ and so on.

create table audit_events (id bigint generated by default as identity, occurred_at timestamp(6) with time zone not null, recorded_at timestamp(6) with time zone not null, outcome varchar(20) not null, actor_role varchar(30), entity_type varchar(40), action varchar(60) not null, source_service varchar(60) not null, event_hash varchar(64) not null, previous_hash varchar(64), actor_username varchar(120), correlation_id varchar(120), entity_id varchar(120), operation_id varchar(120), details oid, primary key (id));
create table idempotency_records (completed_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone not null, id bigint generated by default as identity, version bigint not null, status varchar(20) not null check (status in ('IN_PROGRESS','COMPLETED','FAILED')), result_ref varchar(60), scope varchar(60) not null, request_hash varchar(64) not null, created_by varchar(120), idempotency_key varchar(120) not null, failure_reason varchar(500), response_payload oid, primary key (id), constraint uk_idempotency_scope_key unique (scope, idempotency_key));
create table resource_lock_audit (event_at timestamp(6) with time zone not null, fencing_token bigint, held_millis bigint, id bigint generated by default as identity, action varchar(20) not null check (action in ('ACQUIRED','STOLEN','REENTERED','WAIT_TIMEOUT','RELEASED','RENEWED','LOST','REAPED')), operation_id varchar(120), owner_node varchar(120), owner_token varchar(120), owner_user varchar(120), lock_key varchar(200) not null, detail varchar(500), primary key (id));
create table resource_locks (acquire_count bigint not null, acquired_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone, fencing_token bigint not null, id bigint generated by default as identity, released_at timestamp(6) with time zone, resource_type varchar(50) not null, operation_id varchar(120), owner_node varchar(120), owner_token varchar(120), owner_user varchar(120), resource_id varchar(120) not null, lock_key varchar(200) not null unique, primary key (id));
create index ix_audit_action on audit_events (action);
create index ix_audit_entity on audit_events (entity_type, entity_id);
create index ix_audit_actor on audit_events (actor_username);
create index ix_audit_occurred on audit_events (occurred_at);
create index ix_audit_operation on audit_events (operation_id);
create index ix_audit_correlation on audit_events (correlation_id);
create index ix_idempotency_expires on idempotency_records (expires_at);
create index ix_lock_audit_key on resource_lock_audit (lock_key);
create index ix_lock_audit_at on resource_lock_audit (event_at);
create index ix_lock_audit_operation on resource_lock_audit (operation_id);
create index ix_resource_locks_expires on resource_locks (expires_at);
create index ix_resource_locks_owner on resource_locks (owner_token);
