server:
  port: 8080

spring:
  application:
    name: retailbank-api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: DEBUG