-- Baseline schema for retailbank-account-service (h2).
--
-- Generated from the JPA mappings, so the migration and the entities agree by construction.
-- Hibernate runs in 'validate' mode against this: a mapping change without a matching migration
-- stops the service at startup rather than letting the schema drift silently.
--
-- Never edit this file once it has been applied anywhere. Add V2__, V3__ and so on.

create table account_change_history (account_id bigint not null, changed_at timestamp(6) not null, id bigint generated by default as identity, field_name varchar(60) not null, changed_by varchar(120) not null, new_value varchar(255), old_value varchar(255), reason varchar(255), primary key (id));
create table accounts (balance numeric(19,2) not null, currency varchar(3) not null, daily_limit_date date, daily_transfer_limit numeric(19,2) not null, daily_transferred_amount numeric(19,2) not null, minimum_balance numeric(19,2) not null, overdraft_allowed boolean not null, overdraft_limit numeric(19,2) not null, closed_at timestamp(6), created_at timestamp(6) not null, customer_id bigint not null, id bigint generated by default as identity, last_fencing_token bigint, opened_at timestamp(6) not null, updated_at timestamp(6) not null, version bigint not null, account_number varchar(30) not null unique, account_type enum ('CURRENT','FIXED_DEPOSIT','SALARY','SAVINGS') not null, status enum ('ACTIVE','CLOSED','FROZEN','INACTIVE') not null, primary key (id));
create table idempotency_records (completed_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone not null, id bigint generated by default as identity, version bigint not null, result_ref varchar(60), scope varchar(60) not null, request_hash varchar(64) not null, created_by varchar(120), idempotency_key varchar(120) not null, failure_reason varchar(500), response_payload clob, status enum ('COMPLETED','FAILED','IN_PROGRESS') not null, primary key (id), constraint uk_idempotency_scope_key unique (scope, idempotency_key));
create table ledger_entries (amount numeric(19,2) not null, balance_after numeric(19,2) not null, currency varchar(3) not null, account_id bigint not null, counterparty_account_id bigint, fencing_token bigint, id bigint generated by default as identity, posted_at timestamp(6) not null, account_number varchar(30) not null, entry_ref varchar(40) not null unique, reverses_entry_ref varchar(40), reference varchar(60) not null, operation_id varchar(120), posted_by varchar(120), description varchar(255), direction enum ('CREDIT','DEBIT') not null, movement_type enum ('DEPOSIT','FEE','INTEREST','LOAN_DISBURSEMENT','LOAN_REPAYMENT','REVERSAL','TRANSFER_IN','TRANSFER_OUT','WITHDRAWAL') not null, primary key (id));
create table resource_lock_audit (event_at timestamp(6) with time zone not null, fencing_token bigint, held_millis bigint, id bigint generated by default as identity, operation_id varchar(120), owner_node varchar(120), owner_token varchar(120), owner_user varchar(120), lock_key varchar(200) not null, detail varchar(500), action enum ('ACQUIRED','LOST','REAPED','REENTERED','RELEASED','RENEWED','STOLEN','WAIT_TIMEOUT') not null, primary key (id));
create table resource_locks (acquire_count bigint not null, acquired_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone, fencing_token bigint not null, id bigint generated by default as identity, released_at timestamp(6) with time zone, resource_type varchar(50) not null, operation_id varchar(120), owner_node varchar(120), owner_token varchar(120), owner_user varchar(120), resource_id varchar(120) not null, lock_key varchar(200) not null unique, primary key (id));
create index ix_acct_history_account on account_change_history (account_id);
create index ix_acct_history_at on account_change_history (changed_at);
create index ix_accounts_customer on accounts (customer_id);
create index ix_accounts_status on accounts (status);
create index ix_idempotency_expires on idempotency_records (expires_at);
create index ix_ledger_account_time on ledger_entries (account_id, posted_at);
create index ix_ledger_reference on ledger_entries (reference);
create index ix_ledger_operation on ledger_entries (operation_id);
create index ix_lock_audit_key on resource_lock_audit (lock_key);
create index ix_lock_audit_at on resource_lock_audit (event_at);
create index ix_lock_audit_operation on resource_lock_audit (operation_id);
create index ix_resource_locks_expires on resource_locks (expires_at);
create index ix_resource_locks_owner on resource_locks (owner_token);
