-- Baseline schema for retailbank-loan-service (postgresql).
--
-- Generated from the JPA mappings, so the migration and the entities agree by construction.
-- Hibernate runs in 'validate' mode against this: a mapping change without a matching migration
-- stops the service at startup rather than letting the schema drift silently.
--
-- Never edit this file once it has been applied anywhere. Add V2__, V3__ and so on.

create table idempotency_records (completed_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone not null, id bigint generated by default as identity, version bigint not null, status varchar(20) not null check (status in ('IN_PROGRESS','COMPLETED','FAILED')), result_ref varchar(60), scope varchar(60) not null, request_hash varchar(64) not null, created_by varchar(120), idempotency_key varchar(120) not null, failure_reason varchar(500), response_payload oid, primary key (id), constraint uk_idempotency_scope_key unique (scope, idempotency_key));
create table loan_repayments (due_date date not null, emi_amount numeric(19,2) not null, installment_number integer not null, interest_component numeric(19,2) not null, outstanding_after numeric(19,2) not null, paid_amount numeric(19,2) not null, principal_component numeric(19,2) not null, id bigint generated by default as identity, loan_id bigint not null, paid_at timestamp(6), version bigint not null, status varchar(20) not null check (status in ('PENDING','PARTIALLY_PAID','PAID','OVERDUE')), payment_reference varchar(40), primary key (id), constraint uk_repayment_loan_installment unique (loan_id, installment_number));
create table loans (annual_income_at_application numeric(19,2), credit_score_at_application integer, currency varchar(3) not null, emi_amount numeric(19,2), first_due_date date, interest_rate numeric(6,3) not null, outstanding_principal numeric(19,2) not null, principal numeric(19,2) not null, tenure_months integer not null, total_interest numeric(19,2), total_repaid numeric(19,2) not null, applied_at timestamp(6) not null, closed_at timestamp(6), created_at timestamp(6) not null, customer_id bigint not null, decided_at timestamp(6), disbursed_at timestamp(6), disbursement_account_id bigint not null, disbursement_started_at timestamp(6), id bigint generated by default as identity, updated_at timestamp(6) not null, version bigint not null, loan_type varchar(20) not null check (loan_type in ('PERSONAL','HOME','VEHICLE','EDUCATION')), status varchar(20) not null check (status in ('APPLIED','APPROVED','REJECTED','DISBURSING','DISBURSED','CLOSED','DEFAULTED')), disbursement_reference varchar(40), loan_ref varchar(40) not null unique, decided_by varchar(120), decision_reason varchar(500), primary key (id));
create table resource_lock_audit (event_at timestamp(6) with time zone not null, fencing_token bigint, held_millis bigint, id bigint generated by default as identity, action varchar(20) not null check (action in ('ACQUIRED','STOLEN','REENTERED','WAIT_TIMEOUT','RELEASED','RENEWED','LOST','REAPED')), operation_id varchar(120), owner_node varchar(120), owner_token varchar(120), owner_user varchar(120), lock_key varchar(200) not null, detail varchar(500), primary key (id));
create table resource_locks (acquire_count bigint not null, acquired_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone, fencing_token bigint not null, id bigint generated by default as identity, released_at timestamp(6) with time zone, resource_type varchar(50) not null, operation_id varchar(120), owner_node varchar(120), owner_token varchar(120), owner_user varchar(120), resource_id varchar(120) not null, lock_key varchar(200) not null unique, primary key (id));
create index ix_idempotency_expires on idempotency_records (expires_at);
create index ix_repayments_loan on loan_repayments (loan_id);
create index ix_repayments_due on loan_repayments (due_date);
create index ix_repayments_status on loan_repayments (status);
create index ix_loans_customer on loans (customer_id);
create index ix_loans_status on loans (status);
create index ix_lock_audit_key on resource_lock_audit (lock_key);
create index ix_lock_audit_at on resource_lock_audit (event_at);
create index ix_lock_audit_operation on resource_lock_audit (operation_id);
create index ix_resource_locks_expires on resource_locks (expires_at);
create index ix_resource_locks_owner on resource_locks (owner_token);
alter table if exists loan_repayments add constraint FKmvfjvk48bhsvwbdis0s9uwn1t foreign key (loan_id) references loans;
