-- Baseline schema for retailbank-customer-service (postgresql).
--
-- Generated from the JPA mappings, so the migration and the entities agree by construction.
-- Hibernate runs in 'validate' mode against this: a mapping change without a matching migration
-- stops the service at startup rather than letting the schema drift silently.
--
-- Never edit this file once it has been applied anywhere. Add V2__, V3__ and so on.

create table customers (annual_income numeric(19,2), credit_score integer check ((credit_score>=300) and (credit_score<=900)), date_of_birth date, created_at timestamp(6) not null, id bigint generated by default as identity, kyc_verified_at timestamp(6), updated_at timestamp(6) not null, version bigint not null, kyc_status varchar(20) not null check (kyc_status in ('PENDING','VERIFIED','REJECTED')), status varchar(20) not null check (status in ('ACTIVE','BLOCKED','CLOSED')), customer_number varchar(30) not null unique, employment_type varchar(30) check (employment_type in ('SALARIED','SELF_EMPLOYED','BUSINESS','RETIRED','STUDENT','UNEMPLOYED')), email_index varchar(64), pan_index varchar(64), phone_index varchar(64), first_name varchar(100) not null, last_name varchar(100) not null, middle_name varchar(100), kyc_verified_by varchar(120), kyc_remarks varchar(500), aadhaar_number varchar(512), pan_number varchar(512), phone varchar(512) not null, customer_address varchar(255) not null, email varchar(255) not null, primary key (id), constraint uk_customers_email_index unique (email_index), constraint uk_customers_phone_index unique (phone_index));
create table idempotency_records (completed_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone not null, id bigint generated by default as identity, version bigint not null, status varchar(20) not null check (status in ('IN_PROGRESS','COMPLETED','FAILED')), result_ref varchar(60), scope varchar(60) not null, request_hash varchar(64) not null, created_by varchar(120), idempotency_key varchar(120) not null, failure_reason varchar(500), response_payload oid, primary key (id), constraint uk_idempotency_scope_key unique (scope, idempotency_key));
create table resource_lock_audit (event_at timestamp(6) with time zone not null, fencing_token bigint, held_millis bigint, id bigint generated by default as identity, action varchar(20) not null check (action in ('ACQUIRED','STOLEN','REENTERED','WAIT_TIMEOUT','RELEASED','RENEWED','LOST','REAPED')), operation_id varchar(120), owner_node varchar(120), owner_token varchar(120), owner_user varchar(120), lock_key varchar(200) not null, detail varchar(500), primary key (id));
create table resource_locks (acquire_count bigint not null, acquired_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone, fencing_token bigint not null, id bigint generated by default as identity, released_at timestamp(6) with time zone, resource_type varchar(50) not null, operation_id varchar(120), owner_node varchar(120), owner_token varchar(120), owner_user varchar(120), resource_id varchar(120) not null, lock_key varchar(200) not null unique, primary key (id));
create index ix_customers_kyc on customers (kyc_status);
create index ix_customers_last_name on customers (last_name);
create index ix_customers_pan_index on customers (pan_index);
create index ix_idempotency_expires on idempotency_records (expires_at);
create index ix_lock_audit_key on resource_lock_audit (lock_key);
create index ix_lock_audit_at on resource_lock_audit (event_at);
create index ix_lock_audit_operation on resource_lock_audit (operation_id);
create index ix_resource_locks_expires on resource_locks (expires_at);
create index ix_resource_locks_owner on resource_locks (owner_token);
