-- Baseline schema for retailbank-transaction-service (postgresql).
--
-- Generated from the JPA mappings, so the migration and the entities agree by construction.
-- Hibernate runs in 'validate' mode against this: a mapping change without a matching migration
-- stops the service at startup rather than letting the schema drift silently.
--
-- Never edit this file once it has been applied anywhere. Add V2__, V3__ and so on.

create table idempotency_records (completed_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone not null, id bigint generated by default as identity, version bigint not null, status varchar(20) not null check (status in ('IN_PROGRESS','COMPLETED','FAILED')), result_ref varchar(60), scope varchar(60) not null, request_hash varchar(64) not null, created_by varchar(120), idempotency_key varchar(120) not null, failure_reason varchar(500), response_payload oid, primary key (id), constraint uk_idempotency_scope_key unique (scope, idempotency_key));
create table resource_lock_audit (event_at timestamp(6) with time zone not null, fencing_token bigint, held_millis bigint, id bigint generated by default as identity, action varchar(20) not null check (action in ('ACQUIRED','STOLEN','REENTERED','WAIT_TIMEOUT','RELEASED','RENEWED','LOST','REAPED')), operation_id varchar(120), owner_node varchar(120), owner_token varchar(120), owner_user varchar(120), lock_key varchar(200) not null, detail varchar(500), primary key (id));
create table resource_locks (acquire_count bigint not null, acquired_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone, fencing_token bigint not null, id bigint generated by default as identity, released_at timestamp(6) with time zone, resource_type varchar(50) not null, operation_id varchar(120), owner_node varchar(120), owner_token varchar(120), owner_user varchar(120), resource_id varchar(120) not null, lock_key varchar(200) not null unique, primary key (id));
create table transactions (amount numeric(19,2) not null, balance_after numeric(19,2), currency varchar(3) not null, completed_at timestamp(6), created_at timestamp(6) not null, from_account_id bigint, id bigint generated by default as identity, owner_customer_id bigint, to_account_id bigint, version bigint not null, status varchar(20) not null check (status in ('PENDING','SUCCESS','FAILED','REVERSED')), transaction_type varchar(20) not null check (transaction_type in ('DEPOSIT','WITHDRAWAL','TRANSFER')), credit_entry_ref varchar(40), debit_entry_ref varchar(40), reversal_reference varchar(40), transaction_ref varchar(40) not null unique, idempotency_key varchar(120) unique, initiated_by varchar(120), failure_reason varchar(500), description varchar(255), primary key (id));
create index ix_idempotency_expires on idempotency_records (expires_at);
create index ix_lock_audit_key on resource_lock_audit (lock_key);
create index ix_lock_audit_at on resource_lock_audit (event_at);
create index ix_lock_audit_operation on resource_lock_audit (operation_id);
create index ix_resource_locks_expires on resource_locks (expires_at);
create index ix_resource_locks_owner on resource_locks (owner_token);
create index ix_transactions_from on transactions (from_account_id);
create index ix_transactions_to on transactions (to_account_id);
create index ix_transactions_status on transactions (status);
create index ix_transactions_created on transactions (created_at);
create index ix_transactions_owner on transactions (owner_customer_id);
