server:
  port: 8085

spring:
  application:
    name: retailbank-loan-service

  datasource:
    url: jdbc:postgresql://localhost:5432/retailbank_loan_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: DEBUG